apiVersion: v1
kind: Service
metadata:
  name: dew-hw3-go-consumer
  labels:
    app.kubernetes.io/name: dew-hw3-go-consumer
    app.kubernetes.io/instance: dew-hw3-go-consumer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dew-hw3-go-consumer
    app.kubernetes.io/instance: dew-hw3-go-consumer
